#include <sds_incl.h>
#include "cf_stub.h"

cf_request_handle_t _p0_request_0;
cf_request_handle_t _p0_request_1;
cf_request_handle_t _p0_request_2;
cf_request_handle_t _p0_request_3;
cf_request_handle_t _p0_request_4;
cf_request_handle_t _p0_request_5;
cf_request_handle_t _p0_request_6;
cf_request_handle_t _p0_request_7;
cf_request_handle_t _p0_request_8;
cf_request_handle_t _p0_request_9;
cf_request_handle_t _p0_request_10;
cf_request_handle_t _p0_request_11;
cf_request_handle_t _p0_request_12;
cf_request_handle_t _p0_request_13;
cf_request_handle_t _p0_request_14;
cf_request_handle_t _p0_request_15;
cf_request_handle_t _p0_request_16;
cf_request_handle_t _p0_request_17;
cf_request_handle_t _p0_request_18;
cf_request_handle_t _p0_request_19;
cf_request_handle_t _p0_request_20;
cf_request_handle_t _p0_request_21;
cf_request_handle_t _p0_request_22;
cf_request_handle_t _p0_request_23;

unsigned int _p0_I_Stretch2x_HW8_async_8_num_dest;
unsigned int _p0_I_Stretch2x_HW7_async_7_num_dest;
unsigned int _p0_I_Stretch2x_HW6_async_6_num_dest;
unsigned int _p0_I_Stretch2x_HW5_async_5_num_dest;
unsigned int _p0_I_Stretch2x_HW4_async_4_num_dest;
unsigned int _p0_I_Stretch2x_HW3_async_3_num_dest;
unsigned int _p0_I_Stretch2x_HW2_async_2_num_dest;
unsigned int _p0_I_Stretch2x_HW1_async_1_num_dest;

